### ISSUE TITLE
Any chance of upgrading this to support 3.1

### ISSUE THREAD

**Issue by shereefb** [recurser/rails-kitchen-sink#1]
I'm a huge fan of the kitchen sink, and would love to see it support rails 3.1.

Thanks for all the hard work!

**Comment by recurser** [comment]
Hey shereefb, yes it's definitely going to happen - will probably drop support for 3.0 and focus on 3.1 from now on. Check back in a couple of weeks and hopefully I should have something.

**Comment by shereefb** [comment]
Excellent! You guys rock. Kitchen sink has saved me dozens and dozens of
hours. Really appreciate it.

On Sat, Jul 30, 2011 at 9:58 PM, recurser <
reply@reply.github.com>wrote:

> Hey shereefb, yes it's definitely going to happen - will probably drop
> support for 3.0 and focus on 3.1 from now on. Check back in a couple of
> weeks and hopefully I should have something.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/recurser/rails-kitchen-sink/issues/1#issuecomment-1693971

## 

we're re-inventing work
check it out www.bettermeans.com

**Comment by recurser** [comment]
@shereefb sorry about the huge delay here :/ Obviously Rails has moved on a lot since this was released, and this repo is no longer really relevant. Closing this...
